### ISSUE TITLE
PublicWhip not functioning for editing divisions

### ISSUE THREAD

**Issue by RichardTaylor** [publicwhip/publicwhip#38]
When trying to edit division description today I first got a series of errors from PublicWhip stating

> 403 Forbidden: Access has been denied

>Sorry, you have been blocked from accessing this page
>You have been blocked from accessing this page as our security system interpreted your request as potentially dangerous. 

Followed shortly after by connections being denied when trying to access division pages, with my browser giving errors eg. 

>Unable to connect
>
>An error occurred during a connection to www.publicwhip.org.uk. 

The latter appears specific to my IP address, perhaps triggered by the former?

**Comment by rbairwell** [comment]
Hi,

Thanks for alerting us to this - it was one of the new mod_security firewalls which triggered certain bits of text in the description. I'm in the process of fixing this now - should be sorted in about 10-20 minutes.

**Comment by rbairwell** [comment]
Hi Richard,

This should be resolved and the associated IP address has been removed from the deny-list and the appropriate mod_security rule has been tweaked.

Sorry about that - please let me know if you encounter other issues on the new server.

Thanks,
Richard

**Comment by RichardTaylor** [comment]
I'm still seeing the 

> 403 Forbidden: Access has been denied 

error when saving a division description

>{"errorType":"403","dateStamp":"2022-08-31T12:58:15+01:00","redirectStatus":"403","requestScheme":"https","url":"\/account\/wiki.php","query":"type=motion&date=2021-01-26&number=215&house=commons&rr=%2Fdivision.php%3Fdate%3D2021-01-26%26house%3Dcommons%26number%3D215","host":"www.publicwhip.org.uk","server":"www.publicwhip.org.uk","serverPort":"443","serverAddr":"185.151.31.138","method":"POST","uniqueid":"Yw9M13-RXleskVaLu_1SMgAAAAQ","adminIp":"yes"}

**Comment by RichardTaylor** [comment]
>I'm still seeing the

>>   403 Forbidden: Access has been denied

>error when saving a division description

Occurs with a new, different, browser too.

**Comment by RichardTaylor** [comment]
I'm back to the "can't connect" errors as well now too. (They were resolved for a few minutes). 

I don't have the required access to reopen this ticket.

**Comment by rbairwell** [comment]
Hi,

Should be fixed again now (turns out I made a slight typo earlier!).

Sorry!
